# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/4.2.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/4.2.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/DATA/qt6pro/radarScan/radarScan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/DATA/qt6pro/radarScan/radarScan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/4.2.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/4.2.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/DATA/qt6pro/radarScan/radarScan/CMakeFiles /Volumes/DATA/qt6pro/radarScan/radarScan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/DATA/qt6pro/radarScan/radarScan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named radarScan

# Build rule for target.
radarScan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 radarScan
.PHONY : radarScan

# fast build rule for target.
radarScan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/build
.PHONY : radarScan/fast

#=============================================================================
# Target rules for targets named radarScan_autogen_timestamp_deps

# Build rule for target.
radarScan_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 radarScan_autogen_timestamp_deps
.PHONY : radarScan_autogen_timestamp_deps

# fast build rule for target.
radarScan_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan_autogen_timestamp_deps.dir/build.make CMakeFiles/radarScan_autogen_timestamp_deps.dir/build
.PHONY : radarScan_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named radarScan_autogen

# Build rule for target.
radarScan_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 radarScan_autogen
.PHONY : radarScan_autogen

# fast build rule for target.
radarScan_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan_autogen.dir/build.make CMakeFiles/radarScan_autogen.dir/build
.PHONY : radarScan_autogen/fast

AudioHealthChecker.o: AudioHealthChecker.cpp.o
.PHONY : AudioHealthChecker.o

# target to build an object file
AudioHealthChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/AudioHealthChecker.cpp.o
.PHONY : AudioHealthChecker.cpp.o

AudioHealthChecker.i: AudioHealthChecker.cpp.i
.PHONY : AudioHealthChecker.i

# target to preprocess a source file
AudioHealthChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/AudioHealthChecker.cpp.i
.PHONY : AudioHealthChecker.cpp.i

AudioHealthChecker.s: AudioHealthChecker.cpp.s
.PHONY : AudioHealthChecker.s

# target to generate assembly for a file
AudioHealthChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/AudioHealthChecker.cpp.s
.PHONY : AudioHealthChecker.cpp.s

Pzem004Tv30Qt.o: Pzem004Tv30Qt.cpp.o
.PHONY : Pzem004Tv30Qt.o

# target to build an object file
Pzem004Tv30Qt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/Pzem004Tv30Qt.cpp.o
.PHONY : Pzem004Tv30Qt.cpp.o

Pzem004Tv30Qt.i: Pzem004Tv30Qt.cpp.i
.PHONY : Pzem004Tv30Qt.i

# target to preprocess a source file
Pzem004Tv30Qt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/Pzem004Tv30Qt.cpp.i
.PHONY : Pzem004Tv30Qt.cpp.i

Pzem004Tv30Qt.s: Pzem004Tv30Qt.cpp.s
.PHONY : Pzem004Tv30Qt.s

# target to generate assembly for a file
Pzem004Tv30Qt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/Pzem004Tv30Qt.cpp.s
.PHONY : Pzem004Tv30Qt.cpp.s

audioworker.o: audioworker.cpp.o
.PHONY : audioworker.o

# target to build an object file
audioworker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/audioworker.cpp.o
.PHONY : audioworker.cpp.o

audioworker.i: audioworker.cpp.i
.PHONY : audioworker.i

# target to preprocess a source file
audioworker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/audioworker.cpp.i
.PHONY : audioworker.cpp.i

audioworker.s: audioworker.cpp.s
.PHONY : audioworker.s

# target to generate assembly for a file
audioworker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/audioworker.cpp.s
.PHONY : audioworker.cpp.s

brightness.o: brightness.cpp.o
.PHONY : brightness.o

# target to build an object file
brightness.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/brightness.cpp.o
.PHONY : brightness.cpp.o

brightness.i: brightness.cpp.i
.PHONY : brightness.i

# target to preprocess a source file
brightness.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/brightness.cpp.i
.PHONY : brightness.cpp.i

brightness.s: brightness.cpp.s
.PHONY : brightness.s

# target to generate assembly for a file
brightness.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/brightness.cpp.s
.PHONY : brightness.cpp.s

configmanager.o: configmanager.cpp.o
.PHONY : configmanager.o

# target to build an object file
configmanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/configmanager.cpp.o
.PHONY : configmanager.cpp.o

configmanager.i: configmanager.cpp.i
.PHONY : configmanager.i

# target to preprocess a source file
configmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/configmanager.cpp.i
.PHONY : configmanager.cpp.i

configmanager.s: configmanager.cpp.s
.PHONY : configmanager.s

# target to generate assembly for a file
configmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/configmanager.cpp.s
.PHONY : configmanager.cpp.s

gpio.o: gpio.cpp.o
.PHONY : gpio.o

# target to build an object file
gpio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/gpio.cpp.o
.PHONY : gpio.cpp.o

gpio.i: gpio.cpp.i
.PHONY : gpio.i

# target to preprocess a source file
gpio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/gpio.cpp.i
.PHONY : gpio.cpp.i

gpio.s: gpio.cpp.s
.PHONY : gpio.s

# target to generate assembly for a file
gpio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/gpio.cpp.s
.PHONY : gpio.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

networksetting.o: networksetting.cpp.o
.PHONY : networksetting.o

# target to build an object file
networksetting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/networksetting.cpp.o
.PHONY : networksetting.cpp.o

networksetting.i: networksetting.cpp.i
.PHONY : networksetting.i

# target to preprocess a source file
networksetting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/networksetting.cpp.i
.PHONY : networksetting.cpp.i

networksetting.s: networksetting.cpp.s
.PHONY : networksetting.s

# target to generate assembly for a file
networksetting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/networksetting.cpp.s
.PHONY : networksetting.cpp.s

payloadprocessor.o: payloadprocessor.cpp.o
.PHONY : payloadprocessor.o

# target to build an object file
payloadprocessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/payloadprocessor.cpp.o
.PHONY : payloadprocessor.cpp.o

payloadprocessor.i: payloadprocessor.cpp.i
.PHONY : payloadprocessor.i

# target to preprocess a source file
payloadprocessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/payloadprocessor.cpp.i
.PHONY : payloadprocessor.cpp.i

payloadprocessor.s: payloadprocessor.cpp.s
.PHONY : payloadprocessor.s

# target to generate assembly for a file
payloadprocessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/payloadprocessor.cpp.s
.PHONY : payloadprocessor.cpp.s

qcustomplot.o: qcustomplot.cpp.o
.PHONY : qcustomplot.o

# target to build an object file
qcustomplot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/qcustomplot.cpp.o
.PHONY : qcustomplot.cpp.o

qcustomplot.i: qcustomplot.cpp.i
.PHONY : qcustomplot.i

# target to preprocess a source file
qcustomplot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/qcustomplot.cpp.i
.PHONY : qcustomplot.cpp.i

qcustomplot.s: qcustomplot.cpp.s
.PHONY : qcustomplot.s

# target to generate assembly for a file
qcustomplot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/qcustomplot.cpp.s
.PHONY : qcustomplot.cpp.s

radarScan_autogen/mocs_compilation.o: radarScan_autogen/mocs_compilation.cpp.o
.PHONY : radarScan_autogen/mocs_compilation.o

# target to build an object file
radarScan_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/radarScan_autogen/mocs_compilation.cpp.o
.PHONY : radarScan_autogen/mocs_compilation.cpp.o

radarScan_autogen/mocs_compilation.i: radarScan_autogen/mocs_compilation.cpp.i
.PHONY : radarScan_autogen/mocs_compilation.i

# target to preprocess a source file
radarScan_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/radarScan_autogen/mocs_compilation.cpp.i
.PHONY : radarScan_autogen/mocs_compilation.cpp.i

radarScan_autogen/mocs_compilation.s: radarScan_autogen/mocs_compilation.cpp.s
.PHONY : radarScan_autogen/mocs_compilation.s

# target to generate assembly for a file
radarScan_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/radarScan_autogen/mocs_compilation.cpp.s
.PHONY : radarScan_autogen/mocs_compilation.cpp.s

socketeventworker.o: socketeventworker.cpp.o
.PHONY : socketeventworker.o

# target to build an object file
socketeventworker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/socketeventworker.cpp.o
.PHONY : socketeventworker.cpp.o

socketeventworker.i: socketeventworker.cpp.i
.PHONY : socketeventworker.i

# target to preprocess a source file
socketeventworker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/socketeventworker.cpp.i
.PHONY : socketeventworker.cpp.i

socketeventworker.s: socketeventworker.cpp.s
.PHONY : socketeventworker.s

# target to generate assembly for a file
socketeventworker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/socketeventworker.cpp.s
.PHONY : socketeventworker.cpp.s

socketioclient.o: socketioclient.cpp.o
.PHONY : socketioclient.o

# target to build an object file
socketioclient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/socketioclient.cpp.o
.PHONY : socketioclient.cpp.o

socketioclient.i: socketioclient.cpp.i
.PHONY : socketioclient.i

# target to preprocess a source file
socketioclient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/socketioclient.cpp.i
.PHONY : socketioclient.cpp.i

socketioclient.s: socketioclient.cpp.s
.PHONY : socketioclient.s

# target to generate assembly for a file
socketioclient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/socketioclient.cpp.s
.PHONY : socketioclient.cpp.s

systemdmonitorqt.o: systemdmonitorqt.cpp.o
.PHONY : systemdmonitorqt.o

# target to build an object file
systemdmonitorqt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/systemdmonitorqt.cpp.o
.PHONY : systemdmonitorqt.cpp.o

systemdmonitorqt.i: systemdmonitorqt.cpp.i
.PHONY : systemdmonitorqt.i

# target to preprocess a source file
systemdmonitorqt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/systemdmonitorqt.cpp.i
.PHONY : systemdmonitorqt.cpp.i

systemdmonitorqt.s: systemdmonitorqt.cpp.s
.PHONY : systemdmonitorqt.s

# target to generate assembly for a file
systemdmonitorqt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/systemdmonitorqt.cpp.s
.PHONY : systemdmonitorqt.cpp.s

utilities.o: utilities.cpp.o
.PHONY : utilities.o

# target to build an object file
utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/utilities.cpp.o
.PHONY : utilities.cpp.o

utilities.i: utilities.cpp.i
.PHONY : utilities.i

# target to preprocess a source file
utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/utilities.cpp.i
.PHONY : utilities.cpp.i

utilities.s: utilities.cpp.s
.PHONY : utilities.s

# target to generate assembly for a file
utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/utilities.cpp.s
.PHONY : utilities.cpp.s

volume.o: volume.cpp.o
.PHONY : volume.o

# target to build an object file
volume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/volume.cpp.o
.PHONY : volume.cpp.o

volume.i: volume.cpp.i
.PHONY : volume.i

# target to preprocess a source file
volume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/volume.cpp.i
.PHONY : volume.cpp.i

volume.s: volume.cpp.s
.PHONY : volume.s

# target to generate assembly for a file
volume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radarScan.dir/build.make CMakeFiles/radarScan.dir/volume.cpp.s
.PHONY : volume.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... radarScan_autogen"
	@echo "... radarScan_autogen_timestamp_deps"
	@echo "... radarScan"
	@echo "... AudioHealthChecker.o"
	@echo "... AudioHealthChecker.i"
	@echo "... AudioHealthChecker.s"
	@echo "... Pzem004Tv30Qt.o"
	@echo "... Pzem004Tv30Qt.i"
	@echo "... Pzem004Tv30Qt.s"
	@echo "... audioworker.o"
	@echo "... audioworker.i"
	@echo "... audioworker.s"
	@echo "... brightness.o"
	@echo "... brightness.i"
	@echo "... brightness.s"
	@echo "... configmanager.o"
	@echo "... configmanager.i"
	@echo "... configmanager.s"
	@echo "... gpio.o"
	@echo "... gpio.i"
	@echo "... gpio.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... networksetting.o"
	@echo "... networksetting.i"
	@echo "... networksetting.s"
	@echo "... payloadprocessor.o"
	@echo "... payloadprocessor.i"
	@echo "... payloadprocessor.s"
	@echo "... qcustomplot.o"
	@echo "... qcustomplot.i"
	@echo "... qcustomplot.s"
	@echo "... radarScan_autogen/mocs_compilation.o"
	@echo "... radarScan_autogen/mocs_compilation.i"
	@echo "... radarScan_autogen/mocs_compilation.s"
	@echo "... socketeventworker.o"
	@echo "... socketeventworker.i"
	@echo "... socketeventworker.s"
	@echo "... socketioclient.o"
	@echo "... socketioclient.i"
	@echo "... socketioclient.s"
	@echo "... systemdmonitorqt.o"
	@echo "... systemdmonitorqt.i"
	@echo "... systemdmonitorqt.s"
	@echo "... utilities.o"
	@echo "... utilities.i"
	@echo "... utilities.s"
	@echo "... volume.o"
	@echo "... volume.i"
	@echo "... volume.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

